### ISSUE TITLE
How to make unqlite.dll?

### ISSUE THREAD

**Issue by LeMoussel** [majimenezp/System.Data.Unqlite#4]
In this project there are unqlite.dll. I think the library is compiled from this [Unqlite GitHub source](https://github.com/symisc/unqlite).
I found no information on how to compile Unqlite source with Visual Studio. 
Do you have some informations on how to compile or VS Project to do it?

Thank for your help

**Comment by lukaaash** [comment]
I added Visual Studio solution and projects to my fork a few years ago: https://github.com/lukaaash/unqlite

**Comment by LeMoussel** [comment]
OK. Vu.
Thanks.
